import {spawn} from 'node:child_process';
import fs from 'node:fs/promises';
const children=[];
async function available(url){try{return (await fetch(url)).ok}catch{return false}}
if(!await available('http://127.0.0.1:5174'))children.push(spawn('npm',['run','dev','--','--host','127.0.0.1','--port','5174'],{stdio:'ignore'}));
if(!await available('http://127.0.0.1:9223/json/list'))children.push(spawn('google-chrome',['--headless=new','--no-sandbox','--disable-gpu','--remote-debugging-port=9223','--user-data-dir=/tmp/adat-technology-review','about:blank'],{stdio:'ignore'}));
for(let n=0;n<100 && (!await available('http://127.0.0.1:9223/json/list')||!await available('http://127.0.0.1:5174'));n++)await new Promise(r=>setTimeout(r,200));
const targets=await(await fetch('http://127.0.0.1:9223/json/list')).json();
const ws=new WebSocket(targets.find(t=>t.type==='page').webSocketDebuggerUrl);await new Promise(r=>ws.addEventListener('open',r,{once:true}));
let id=0;const pending=new Map();const exceptions=[];
const send=(method,params={})=>new Promise((resolve,reject)=>{const key=++id;pending.set(key,{resolve,reject});ws.send(JSON.stringify({id:key,method,params}));});
const mainSource = await (await fetch('http://127.0.0.1:5174/src/main.tsx')).text();
const reactPath = mainSource.match(/"([^"\n]*\/react\.js[^"\n]*)"/)[1];
const routerPath = mainSource.match(/"([^"\n]*\/react-router-dom\.js[^"\n]*)"/)[1];
const app=`import React from '${reactPath}';import {Routes,Route} from '${routerPath}';import TechStackTab from '/src/components/dashboard/TechStackTab.tsx';import TechnologyDetailPage from '/src/pages/TechnologyDetailPage.tsx';export default function App(){return React.createElement(Routes,null,React.createElement(Route,{path:'/dashboard',element:React.createElement(TechStackTab)}),React.createElement(Route,{path:'/technologies/:slug',element:React.createElement(TechnologyDetailPage)}));}`;
const firestore=`const store=window.testStore;export function collection(db,name){return {path:name}};export function doc(db,name,id){return {path:name+'/'+id,id}};export const orderBy=()=>{};export const where=()=>{};export const query=(ref)=>ref;export async function getDocs(ref){return {docs:Object.entries(store).filter(([k])=>k.startsWith(ref.path+'/')).map(([path,value])=>({id:path.split('/')[1],data:()=>value}))}};export async function updateDoc(ref,data){store[ref.path]={...store[ref.path],...data}};export async function addDoc(){throw Error('Unexpected add')};export async function deleteDoc(){throw Error('Unexpected delete')};`;
ws.addEventListener('message',async e=>{const m=JSON.parse(e.data);if(m.id){const p=pending.get(m.id);pending.delete(m.id);m.error?p?.reject(m.error):p?.resolve(m.result);}if(m.method==='Runtime.exceptionThrown'){exceptions.push(m.params.exceptionDetails.text);console.log('RUNTIME',m.params.exceptionDetails.exception?.description || m.params.exceptionDetails.text);}if(m.method==='Fetch.requestPaused'){const p=m.params;const url=p.request.url;const source=url.includes('/src/App.tsx')?app:url.includes('/src/lib/firebase.ts')?'export const db = {};':firestore;await send('Fetch.fulfillRequest',{requestId:p.requestId,responseCode:200,responseHeaders:[{name:'Content-Type',value:'text/javascript'}],body:Buffer.from(source).toString('base64')});}});
await send('Page.enable');await send('Runtime.enable');await send('Fetch.enable',{patterns:[{urlPattern:'*/src/App.tsx*'},{urlPattern:'*/src/lib/firebase.ts*'},{urlPattern:'*/firebase_firestore.js*'}]});
await send('Page.addScriptToEvaluateOnNewDocument',{source:`window.testStore=${JSON.stringify({'tech_stack/test':{title:'Frontend',description:'Web technology',themeColor:'blue',categoryIcon:'Code',createdAt:1,technologies:[{name:'React.js',iconUrl:'IconBrandReact',iconType:'library'}]}})}`});
const ev=async expression=>(await send('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true})).result.value;
async function waitFor(expression){for(let i=0;i<150;i++){if(await ev(`Boolean(${expression})`))return;await new Promise(r=>setTimeout(r,150));}console.log('PAGE',await ev('document.body.innerText.slice(0,3000)'));throw Error('Timed out '+expression);}
await send('Emulation.setDeviceMetricsOverride',{width:1440,height:1000,deviceScaleFactor:1,mobile:false});
await send('Page.navigate',{url:'http://127.0.0.1:5174/dashboard'});await waitFor("document.querySelector('table tbody tr button')");
await ev("document.querySelector('table tbody tr button').click()");await waitFor("document.querySelector('details summary')");await ev("document.querySelector('details summary').click()");
await ev(`(()=>{const label=[...document.querySelectorAll('label')].find(l=>l.childNodes[0]?.textContent==='Overview description');const el=label.querySelector('textarea');Object.getOwnPropertyDescriptor(HTMLTextAreaElement.prototype,'value').set.call(el,'Backend edited overview for React.');el.dispatchEvent(new Event('input',{bubbles:true}));})()`);
await ev("document.querySelector('form').requestSubmit()");await waitFor("window.testStore['tech_stack/test'].technologies[0].page?.overview==='Backend edited overview for React.'");console.log('PASS backend detail content saves');
const saved=await ev('window.testStore');await send('Page.addScriptToEvaluateOnNewDocument',{source:`window.testStore=${JSON.stringify(saved)}`});
await send('Page.navigate',{url:'http://127.0.0.1:5174/technologies/reactjs'});await waitFor("document.body.innerText.includes('Backend edited overview for React.')");console.log('PASS public page uses backend content');
if(!await ev("document.querySelectorAll('h3').length>5"))throw Error('Missing sections');console.log('PASS default sections preserved');
await new Promise(r=>setTimeout(r,600));await fs.writeFile('/tmp/adat-technology-desktop.png',Buffer.from((await send('Page.captureScreenshot',{format:'png'})).data,'base64'));
await send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});
if(!await ev('document.documentElement.scrollWidth<=390'))throw Error('Mobile overflow');console.log('PASS mobile layout');
await send('Page.navigate',{url:'http://127.0.0.1:5174/technologies/unknown'});await waitFor("document.body.innerText.includes('Technology not found')");console.log('PASS unknown slug does not display React');
if(exceptions.length)throw Error(exceptions.join(','));console.log('PASS no runtime errors');
ws.close();children.forEach(child=>child.kill());
